apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: ak8-runners-bicep
  namespace: default
spec:
  replicas: 0
  template:
    spec:
      organization: OPM
      image: opmgithubactionsohacr.azurecr.us/runner-image:bicepv0.11.1
      imagePullPolicy: Always
      labels:
        - bicep
        - azure
      env:
      - name: RUNNER_FEATURE_FLAG_EPHEMERAL
        value: "true"
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: ak8-runners-bicep-deployment-autoscaler
  namespace: default
spec:
  scaleTargetRef:
    name: ak8-runners-bicep
  minReplicas: 1
  maxReplicas: 2
  scaleUpTriggers:
  - githubEvent: {}
    duration: "1m"
