apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: ak8-runners-go
  namespace: default
spec:
  replicas: 0
  template:
    spec:
      organization: OPM
      image: opmgithubactionsohacr.azurecr.us/runner-image:go1.17.6
      imagePullPolicy: Always
      labels:
        - go
        - azure
      env:
      - name: RUNNER_FEATURE_FLAG_EPHEMERAL
        value: "true"
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: ak8-runners-go-deployment-autoscaler
  namespace: default
spec:
  scaleTargetRef:
    name: ak8-runners-go
  minReplicas: 1
  maxReplicas: 2
  scaleUpTriggers:
  - githubEvent: {}
    duration: "1m"
